### PR TITLE
[RTM] User statistics design improved

### PR DESCRIPTION
**Pull request by vaceksimon**

### CODE REVIEW

**Comment by paetricc** [comment]
LGTM. What about you, @davidchocholaty?

**Comment by vaceksimon** [comment]
@paetricc I have added 1 more commit with minor changes if you want to check the update.

**Comment by davidchocholaty** [comment]
> LGTM. What about you, @davidchocholaty?

It looks great to me too. IMO ready to merge.

**Comment by davidchocholaty** [comment]
@vaceksimon Thank you :+1:

**Pull request merged**
